powsybl/powsybl-afs

- afs-core/src/main/java/com/powsybl/afs/AppFileSystem.java
- afs-core/src/test/java/com/powsybl/afs/AfsBaseTest.java
- [ x] The commit message follows our guidelines
feature
Did not find a way to retrieve a node without providing its class.
Add a method that fetch a node without this prior information.
> Add class agnostic fetch node on appfilesystem

- afs-ext-base/src/main/java/com/powsybl/afs/ext/base/VirtualCase.java
- [x ] The commit message follows our guidelines
Bug fix
Network cache isn't invalidated when dependencies are changed
Invalidation occur when dependencies are changed
> Invalidate network on dep changes

- afs-core/src/main/java/com/powsybl/afs/AfsCircularDependencyException.java
- afs-core/src/main/java/com/powsybl/afs/ProjectFile.java
- afs-core/src/test/java/com/powsybl/afs/AfsBaseTest.java
- afs-ext-base/pom.xml
- afs-ext-base/src/main/java/com/powsybl/afs/ext/base/AbstractScript.java
- afs-ext-base/src/main/java/com/powsybl/afs/ext/base/VirtualCase.java
- afs-ext-base/src/test/java/com/powsybl/afs/ext/base/ModificationScriptTest.java
- afs-ext-base/src/test/java/com/powsybl/afs/ext/base/VirtualCaseTest.java
- [x ] The commit message follows our guidelines
https://github.com/powsybl/powsybl-core/issues/603
> Add a circular dependency check on some objects deps

- .github/workflows/maven.yml
N/A
Continuous Integration
Powsybl-core was build during CI because we depend on snapshot
Powsybl-core is not build during CI anymore because we depend on release
(if any of the …
> Remove the compilation of powsybl-core during CI

- afs-ext-base/src/main/java/com/powsybl/afs/ext/base/ImportedCase.java
bug fix
Cache invalidation is done after deletion, which cause an error since the object is deleted and not found on invalidation.
Move invalidation of network cache in invalidate general method
> Remove network cache invalidation on delete

- afs-ext-base/pom.xml
- afs-ext-base/src/main/java/com/powsybl/afs/ext/base/AbstractScript.java
- afs-ext-base/src/main/java/com/powsybl/afs/ext/base/GenericScript.java
- afs-ext-base/src/main/java/com/powsybl/afs/ext/base/GenericScriptBuilder.java
- afs-ext-base/src/main/java/com/powsybl/afs/ext/base/GenericScriptExtension.java
- afs-ext-base/src/test/java/com/powsybl/afs/ext/base/ModificationScriptTest.java
bug fix
Generic script afs object does not have an associated extension
The extension now allows the creation of generic script objects
> Add missing GenericScript extension

- afs-scripting/pom.xml
- pom.xml
bug fix
The javadoc is missing for groovy only module
The groovydoc is generated into the expected module javadoc
> Javadoc for groovy only module

- afs-scripting/pom.xml
- pom.xml
bug fix
The javadoc is missing for groovy only module
The groovydoc is generated into the expected module javadoc
> fix javadoc

- afs-storage-api/src/main/java/com/powsybl/afs/storage/AppStorageArchive.java
Signed-off-by: berthaultval <valentinberthault@outlook.fr>
Bug fix
Some timeseries have a dot at the end of their name. Therefore when we archive Windows delete these dots and when we unarchive  the timeseries are not present because metadata and the name of the folder are different.
When we archive the extension ".ts" is added.
> Add extension ".ts" when archive time-series

- afs-ws/afs-ws-client-utils/src/main/java/com/powsybl/afs/ws/client/utils/ClientUtils.java
- afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageServer.java
Signed-off-by: yichen88 <tang.yichenyves@gmail.com>
#39 
Bug fix
> Fix response status if not found (#39)

- afs-core/src/main/java/com/powsybl/afs/LocalTaskMonitor.java
- afs-core/src/main/java/com/powsybl/afs/TaskMonitor.java
- afs-core/src/test/java/com/powsybl/afs/LocalTaskMonitorTest.java
feature
task is unaware of the afs node source that lead to its creation
when task are created from a project file, the id of the node is attached to the task
> Add node ref id in tasks

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-mapdb-storage/src/main/java/com/powsybl/afs/mapdb/storage/MapDbAppStorage.java
- afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
bug fix
When a node is deleted, there is no event indicating to other object that the dependency to that object was also removed.
This prevent from correctly updating objects for this loss
The corresponding events to the dependencies deletions are added.
> Add missing dependency removed event on node deletion

- afs-core/src/main/java/com/powsybl/afs/AbstractNodeBase.java
- afs-core/src/main/java/com/powsybl/afs/AppFileSystemTool.java
- afs-core/src/main/java/com/powsybl/afs/ProjectFileExtension.java
- afs-core/src/test/java/com/powsybl/afs/AfsBaseTest.java
- afs-storage-api/src/main/java/com/powsybl/afs/storage/AppStorageArchive.java
Signed-off-by: berthaultval <valentinberthault@outlook.fr>
feature
When you archive with the option to delete the results, the time series are archived with the metrix and the multi-situation.
when you archive with the option to delete the results, the time series aren't archived with the metrix and the multi-situation
> archive keep result time series

- afs-core/src/main/java/com/powsybl/afs/AppData.java
refacto
we cannot acces AppData::findService outside of a Node. But there is a need for global services that need access to service extension of appadata.
Allow access to appdata service extension from other object than afs nodes.
> Set findService to public

- afs-core/src/main/java/com/powsybl/afs/AppFileSystem.java
- afs-core/src/main/java/com/powsybl/afs/OrderedDependencyManager.java
- afs-core/src/main/java/com/powsybl/afs/Project.java
- afs-core/src/main/java/com/powsybl/afs/ProjectFile.java
- afs-core/src/main/java/com/powsybl/afs/ProjectFileCreationContext.java
feature
When manipulating afs object, a listener is always added. In our cases this is unwanted, especially when browsing large collection of objects. This can cause a very large listener count that needlessly using cpu time.
We can instanciate afs object without connecting them to the event system. When fetching an object dependencies, this is now the default behavior.
**Does this PR introduce a breaking change or …
> Remove node event connection (listener) when fetching dependencies

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-cassandra/src/test/java/com/powsybl/afs/cassandra/CassandraDataSplitTest.java
Bug fix
When using `CassandraAppStorage.writeBinaryData` we receive a `CassandraAppStorage.BinaryDataOutputStream`. I guess it should be intended that when writting on this outputstream the previous data is cleared.
This is not the case since if previous data were larger (with a chunk count greater than the chunk count of the new data), it would result in corrupted data as the reading of this data node would include the new data plus the last chunk not overlapped from the …
> Fix cassandra data node OutputStream potential overlap

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-cassandra/src/test/java/com/powsybl/afs/cassandra/CassandraDataSplitTest.java
bug fix
Also (not fixed in this PR), the chunk size is not enforced if the write buffer length used with this outputstream is greater than the chunk size.
For instance:
```
String nodeId = "someId";
String dataNodeName = "somedataname";
byte[] data = new byte[N]; // where N is greater than chunk size
Arrays.fill(data, (byte)0);
try(BinaryDataOutputStream os = new BinaryDataOutputStream(nodeId, dataNodeName))  { …
```
> Enforce chunk size in cassandra data output stream

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
Bug fix
Since https://github.com/powsybl/powsybl-afs/pull/55, the data names are removed before any new write to the data output stream.
It happens that the recreation of the data name at the end, protected with ifNotExists, does not pick up consistently the prior deletion, and therefore sometimes does not recreate the data name.
Now the data name is always created (removing the ifNotExists clause since the data name is …
> Remove ifnotexist when inserting node_data_name

- afs-spring-server/src/main/java/com/powsybl/afs/server/StorageSwaggerConfig.java
- pom.xml
Bug fix
swagger-ui does not show up in third party projects using powsybl-afs-spring-server
swagger-ui shows up correctly
> [afs-spring-server] Back to springfox v2.9.2, v2.10.5 is broken

- afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageApplication.java
The context classloader can be the wrong one (and ServiceLoader.load returns an empty list)
when you are calling ServiceLoader.load in the ForkJoinPool.commonPool() (or any other thread pool)
and you have your classes in another classloader than the AppClassLoader (=system classloader).
This is the case when using a springboot fat jar, or when deploying the code in a war in an application
server, or when using mvn exec:java
Signed-off-by: Jon Harper <jon.harper87@gmail.com> …
> use ServiceLoader.load with the current classloader instead of the context classloader

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
Bug
In `CassandraAppStorage`, when updating a node's data, the corresponding event is sent at the start of writing instead of being sent when writing is done.
`NodeDataUpdated` events are sent when writing is finished.
> Fix data updated events in cassandra implementation

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-cassandra/src/test/java/com/powsybl/afs/cassandra/CassandraAppStorageTest.java
Bug fix
In `CassandraAppStorage`, getting the parent of a node may fail if one of its children is inconsistent. This should not happen since there is no relation at all between this child consistency and the node itself or its parent.
Actually, it does not really make sense to check consistency, even for the parent, here.
No check on consistency when getting parent node.
> Fixes cassandra "get parent" behaviour

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-cassandra/src/test/java/com/powsybl/afs/cassandra/CassandraAppStorageTest.java
Performance/memory usage improvement
Cassandra queries for static node data (id, parent, ...) get all matching rows, which means 1 row per child of the node. If the node has a lot of children, this can lead to a lot of uselessly duplicated data received from cassandra.
In production system, we observe a surprisingly larger execution time for `getParent` requests than for other requests. We suspect it comes from those unnecessary duplicates.
(**confirmed, see benchmark below**) …
> Select distinct for static queries

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-cassandra/src/test/java/com/powsybl/afs/cassandra/CassandraAppStorageTest.java
Signed-off-by: yichen88 <tang.yichenyves@gmail.com>
#87 
> Add orphan node check

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-cassandra/src/test/java/com/powsybl/afs/cassandra/CassandraAppStorageTest.java
> Fsck orphan data

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-mapdb-storage/src/main/java/com/powsybl/afs/mapdb/storage/MapDbAppStorage.java
- afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
Bug fix.
When calling `node.delete()`, some events are not raised:
* children nodes removal events
* data removal events
All events corresponding to the elements actually deleted are raised.
> Fix node deletion events in mapdb and cassandra implementations

- pom.xml
Bugfix
Our code references java 8 classes from javaEE 7.0,
which does not seem to work well while generating javadoc.
We use the "release=8" option to ensure source compatibility.
> Workaround javadoc generation issue with JDK 11

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
Signed-off-by: Quentin <quentin.capy@rte-france.com>
- [X ] The commit message follows our guidelines
No
Fix lost of metadata while renaming child.
while calling rename, the metadata are lost 
keep metadata
> fix metadata while rename

- afs-action-dsl/pom.xml
- afs-cassandra/pom.xml
- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-contingency/pom.xml
- afs-core/pom.xml
- afs-distribution/pom.xml
- afs-ext-base/pom.xml
- afs-local/pom.xml
- afs-mapdb-storage/pom.xml
- afs-mapdb/pom.xml
- afs-network/afs-network-client/pom.xml
- afs-network/afs-network-server/pom.xml
- afs-network/pom.xml
- afs-scripting/pom.xml
- afs-security-analysis-local/pom.xml
- afs-security-analysis/pom.xml
- afs-spring-server/pom.xml
- afs-storage-api/pom.xml
- afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
- afs-ws/afs-ws-client-utils/pom.xml
- afs-ws/afs-ws-client/pom.xml
- afs-ws/afs-ws-server-utils/pom.xml
- afs-ws/afs-ws-server/pom.xml
- afs-ws/afs-ws-storage/pom.xml
- afs-ws/afs-ws-utils/pom.xml
- afs-ws/pom.xml
- pom.xml
Bugfix
The cassandra implementation of AFS does not store correctly the node version, but 0 instead.
This was not covered by unit tests.
Version is correctly stored and retrieved.
> Cassandra fix node version

- afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
- afs-cassandra/src/test/java/com/powsybl/afs/cassandra/CassandraAppStorageTest.java
- afs-cassandra/src/test/java/com/powsybl/afs/cassandra/CassandraRenameIssueTest.java
Fix rename, add al primary key while deleting old node.
While renaming a node, all node with the same in the folder name where deleted
only the old renamed node is deleted
> Fix storage node rename to not delete children nodes with same names

- pom.xml
No
Bug fix
In Mapdb pom.xml, the kotlin version is [1.9.22,1.9.99], which means that the last 1.9 version is downloaded, even if it is a snapshot version (which does not work on production environments).
Kotlin dependency is now added in powsybl-afs so that the version can be chosen (1.9.22 as of now). …
> Kotlin downgrade to 1.9.22

- afs-ws/afs-ws-server-utils/pom.xml
- afs-ws/afs-ws-server-utils/src/main/java/com/powsybl/afs/ws/server/utils/AppDataBean.java
- afs-ws/afs-ws-server-utils/src/test/java/com/powsybl/afs/ws/server/utils/AppDataBeanTest.java
> Be able to reinit the connection to the computation manager with no impact on other backend connections

- afs-core/src/main/java/com/powsybl/afs/AppData.java
- afs-core/src/test/java/com/powsybl/afs/AppDataTest.java
- afs-ws/afs-ws-server-utils/src/main/java/com/powsybl/afs/ws/server/utils/AppDataBean.java
- afs-ws/afs-ws-server-utils/src/test/java/com/powsybl/afs/ws/server/utils/AppDataBeanTest.java
No
Feature
The only way to reinitialize the connection manager is to call clean() and init() but these methods also reinitialize other backend connections (Cassandra ...)
The existing clean() and init() methods are still there. A new method reinitComputationManager() is added to reinitialize the computation manager alone without impacting other backend 
**What changes might users need to make in their …
> Delete AppDataBean ComputationManager fields to use those in AppData

- pom.xml
No
Bug fix
Groovydoc was not generated 
Groovydoc is now generated
> Fix groovydoc generation

- .github/workflows/snapshot-ci.yml
No
Feature
Slack notification is sent on every CI launch
Slack notification in only sent if the CI fails or if it was activated manually
> Send Slack notification only on failure or on demand

- afs-action-dsl/src/main/java/com/powsybl/afs/action/dsl/ActionScriptBuilder.java
- afs-action-dsl/src/test/java/com/powsybl/afs/action/dsl/ActionScriptTest.java
- afs-ext-base/src/main/java/com/powsybl/afs/ext/base/ModificationScriptBuilder.java
- afs-ext-base/src/test/java/com/powsybl/afs/ext/base/ModificationScriptTest.java
No
Feature
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
Both `ActionScriptBuilder` and `ModificationScriptBuilder` create scripts using fixed pseudo-class values:
* `ActionScriptBuilder` uses `ActionScript.PSEUDO_CLASS`: "actionScript"
* `ModificationScriptBuilder` uses `ModificationScript.PSEUDO_CLASS`: "modificationScript"
The builders now allow customization of the pseudo-class through the `withPseudoClass(String pseudoClass)` method.
* If a custom pseudo-class is provided …
> Add pseudoClass customization for ModificationScriptBuilder and ActionScriptBuilder

- afs-ext-base/src/main/java/com/powsybl/afs/ext/base/VirtualCase.java
No
Feature
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
Some static attributes in VirtualCase are protected while they could be useful.
Those static attributes are now public
> Make VirtualCase static attributes public
