powsybl/powsybl-afs

afs-core/pom.xml, afs-ext-base/pom.xml, afs-scripting/pom.xml, afs-ws/afs-ws-server/pom.xml, pom.xml
- [ x] The commit message follows our guidelines
fix some core dependencies in pom
=> Fix core dependencies

pom.xml
N/A
Update
Depends on powsybl-core snapshot
Depends on powsybl-core release
=> Change powsybl-core version to current release

afs-core/pom.xml, afs-core/src/main/java/com/powsybl/afs/LocalTaskMonitor.java, afs-core/src/main/java/com/powsybl/afs/TaskCancellableStatusChangeEvent.java, afs-core/src/main/java/com/powsybl/afs/TaskMonitor.java, afs-core/src/test/java/com/powsybl/afs/LocalTaskMonitorTest.java, afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java, afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageServer.java, afs-ws/afs-ws-server/src/test/java/com/powsybl/afs/ws/server/AppStorageServerTest.java, afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/RemoteTaskMonitor.java
- [x ] The commit message follows our guidelines
feature
The task is loosely link to a real computation process
The user can set a CompletableFuture to the task object. This allow cancellation of the process via the task manager.
=> Extend task with optional related future

afs-core/pom.xml, afs-core/src/main/java-templates/com/powsybl/afs/PowsyblAfsVersion.java
- [ x] The commit message follows our guidelines
feature
the template for code versionning is added (used in applications using afs to know which version it has been built on)
=> Add version template

afs-core/src/main/java/com/powsybl/afs/OrderedDependencyManager.java, afs-ext-base/src/main/java/com/powsybl/afs/ext/base/AbstractScript.java, afs-ext-base/src/test/java/com/powsybl/afs/ext/base/ModificationScriptTest.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/InMemoryEventsBus.java
Signed-off-by: Nassirou NAMBIEMA <nassirou.nambiena@rte-france.com>
- [x ] The commit message follows our guidelines
no
bug fix
the dependency cache is not updated correctly
the dependency cache is set to null after dependencies are edited
**Does this PR introduce a breaking change or deprecate an …
=> Update dependency cache

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
N/A
Release
Current version is 3.1.0.-SNAPSHOT
Current version is 3.2.0.-SNAPSHOT
=> Prepare release v3.1.0

afs-core/src/main/java/com/powsybl/afs/AbstractNodeBase.java, afs-core/src/main/java/com/powsybl/afs/AppFileSystemTool.java, afs-core/src/test/java/com/powsybl/afs/AfsBaseTest.java, afs-core/src/test/java/com/powsybl/afs/AppFileSystemToolTest.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/AppStorageArchive.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/Utils.java, afs-storage-api/src/test/java/com/powsybl/afs/storage/UtilsTest.java
feature
When you archive, dependencies aren't archived.
When you archive, you can archive dependencies in the same zip.
when you unarchive, a folder is created with the archive's name and all dependencies are unarchived in the folder.
=> Archive dependencies

afs-security-analysis/pom.xml, pom.xml
upgrade
powsybl-core version is 3.1.0
powsybl-core version is 3.2.0
=> Upgrade powsybl core 3.2.0

afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server-utils/src/main/java/com/powsybl/afs/ws/server/utils/SwaggerConfigExtension.java, afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageApplication.java, afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageServer.java, afs-ws/afs-ws-server/src/test/java/com/powsybl/afs/ws/server/SwaggerExtensionTest.java
feature and docs update
The swagger configuration is defined in this library. When using this lib we cannot override the swagger configuration, especially the scanned packaged and title.
An extension allow afs users to override the swagger configuration to fit their documentation needs.
Also the afs doc is updated
=> Update swagger doc + add swagger config extension

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
N/A
Release
Current version is powsybl-afs v3.2.0-SNAPSHOT
Current version is powsybl-afs v3.3.0-SNAPSHOT
(if any of the questions/checkboxes don't apply, please delete them …
=> Prepare release 3.2.0

afs-core/src/main/java/com/powsybl/afs/AppFileSystem.java, afs-core/src/test/java/com/powsybl/afs/AfsBaseTest.java
Signed-off-by: yichen88 <tang.yichenyves@gmail.com>
=> Add throws exception javadoc on fetchNode()

pom.xml
update
powsybl-core version 3.2
powsybl-core version 3.3
=> Update powsybl-core 3.3

afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageServer.java
log feature
Actions made by user are barely logged. This prove difficult to track what's going on in the server.
Major actions are logged so that analysis in case of production issue is easier.
=> Add more log for server actions

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
N/A
Release
Current version is v3.3.0-SNAPSHOT, based on powsybl-core v3.3.0
Current version is v3.4.0-SNAPSHOT, based on powsybl-core [v3.3.1](https://github.com/powsybl/powsybl-core/releases/tag/v3.3.1)
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …
=> Prepare release v3.3.0

afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server-utils/src/main/java/com/powsybl/afs/ws/server/utils/AfsSimpleSecurityContext.java, afs-ws/afs-ws-server-utils/src/main/java/com/powsybl/afs/ws/server/utils/JwtTokenNeededFilter.java, afs-ws/afs-ws-server-utils/src/test/java/com/powsybl/afs/ws/server/utils/AfsSimpleSecurityContextTest.java, afs-ws/afs-ws-server-utils/src/test/java/com/powsybl/afs/ws/server/utils/CodeCoverageTest.java
feature
When a user authenticate, no security context is created.
When a user authenticate, a security context is created, containing the user principal with username info.
=> Add security context

pom.xml
N/A
Dependency update
powsybl-afs is based on powsybl-core v3.3.1
powsybl-afs is based on powsybl-core v3.3.2
(if any of the questions/checkboxes don't apply, please delete them …
=> Update powsybl-core version to v3.3.2

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
N/A
Release
Current version is v3.4.0-SNAPSHOT
New version is v3.5.0-SNAPSHOT
=> Prepare release 3.4.0

.github/workflows/maven.yml
Sonar analysis with java 8 is not supported anymore
Bug fix
Build fail with sonar
Update github action to use sonar with java 11
=> Use java 11 for sonar analysis

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
=> Prepare release v3.5.0

afs-action-dsl/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-core/src/test/java/com/powsybl/afs/AbstractProjectFileTest.java, afs-ext-base/src/main/java/com/powsybl/afs/ext/base/ImportedCase.java, afs-ext-base/src/main/java/com/powsybl/afs/ext/base/LocalNetworkCacheService.java, afs-ext-base/src/main/java/com/powsybl/afs/ext/base/NetworkCacheService.java, afs-ext-base/src/main/java/com/powsybl/afs/ext/base/ProjectCase.java, afs-ext-base/src/main/java/com/powsybl/afs/ext/base/VirtualCase.java, afs-ext-base/src/test/java/com/powsybl/afs/ext/base/ImportedCaseTest.java, afs-ext-base/src/test/java/com/powsybl/afs/ext/base/VirtualCaseTest.java, afs-network/afs-network-client/src/main/java/com/powsybl/afs/network/client/RemoteNetworkCacheService.java, afs-security-analysis-local/pom.xml
Signed-off-by: funfrockmar <marianne.funfrock@rte-france.com>
=> [Iissue-78] Add NetworkListener on virtual case

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
=> Prepare release v3.6.0

afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java, afs-cassandra/src/test/java/com/powsybl/afs/cassandra/CassandraAppStorageTest.java, afs-core/src/main/java/com/powsybl/afs/AppFileSystem.java, afs-spring-server/src/main/java/com/powsybl/afs/server/StorageServer.java, afs-spring-server/src/test/java/com/powsybl/afs/server/StorageServerTest.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/AppStorage.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/ForwardingAppStorage.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/check/FileSystemCheckIssue.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/check/FileSystemCheckOptions.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/check/FileSystemCheckOptionsBuilder.java, afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageServer.java, afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/RemoteAppStorage.java
Signed-off-by: yichen88 <tang.yichenyves@gmail.com>
#80 
=> Add filesystem checker

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis-local/src/main/java/com/powsybl/afs/security/local/LocalSecurityAnalysisRunningService.java, afs-security-analysis/pom.xml, afs-security-analysis/src/main/java/com/powsybl/afs/security/SubjectInfoInterceptor.java, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
Signed-off-by: Lunarya <capy.quentin.pro@gmail.com>
No it's an update of powsybl-core  to 4.7.0
update of powsybl-core  to 4.7.0
update of powsybl-core  to 4.7.0
(if any of the …
=> Update powsybl core 4.7

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
Bump to minor version v4.1.0:
patch versions will remain in branch v4.0.x
=> Bump to v4.1.0

afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraSimpleContext.java
Signed-off-by: Sylvain Leclerc <sylvain.leclerc@rte-france.com>
Backport a config change which was missed in #108.
All that configuration should be made configurable.
=> Backport cassandra request timeout change from v4.0.x

afs-ext-base/src/main/java/com/powsybl/afs/ext/base/ImportedCaseBuilder.java, afs-ext-base/src/test/java/com/powsybl/afs/ext/base/TestImporter.java, afs-local/src/main/java/com/powsybl/afs/local/storage/LocalCaseScanner.java, afs-security-analysis-local/src/main/java/com/powsybl/afs/security/local/LocalSecurityAnalysisRunningService.java, afs-security-analysis-local/src/test/java/com/powsybl/afs/security/local/SecurityAnalysisProviderMock.java, pom.xml
Signed-off-by: quentin <quentin.capy@rte-france.com>
- [ X] The commit message follows our guidelines
- [ X] Tests for the changes have been added (for bug fixes / features)
- [X ] The *Breaking Change* …
=> update powsybl to 4.10.1

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
Signed-off-by: Sylvain Leclerc <sylvain.leclerc@rte-france.com>
Update version to 5.0.0, for consistency with powsybl-core versioning
=> Bump v5.0.0

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
=> Release v5.0.0

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
=> Release branch v5.0.2

afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java, afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
=> Fix storage of node version in cassandra implementation

afs-core/src/main/java/com/powsybl/afs/AppFileSystem.java
Feature to add the ability to override the project search of a node
Project search is duplicated and does not allow to override search based on file system implementation
Project search is now in a dedicated and overridable method
=> Allow to override filesystem project node search

afs-core/pom.xml, afs-core/src/main/java/com/powsybl/afs/AppFileSystemTool.java, afs-core/src/test/java/com/powsybl/afs/AppFileSystemToolTest.java, afs-ext-base/src/main/java/com/powsybl/afs/ext/base/ImportedCaseBuilder.java, afs-ext-base/src/main/java/com/powsybl/afs/ext/base/ScriptError.java, afs-local/src/main/java/com/powsybl/afs/local/storage/LocalCase.java, afs-local/src/main/java/com/powsybl/afs/local/storage/LocalCaseScanner.java, afs-mapdb-storage/src/main/java/com/powsybl/afs/mapdb/storage/MapDbAppStorage.java, afs-mapdb/src/main/java/com/powsybl/afs/mapdb/MapDbAppFileSystemProvider.java, afs-spring-server/src/main/java/com/powsybl/afs/server/events/TaskEventHandler.java, afs-spring-server/src/main/java/com/powsybl/afs/server/events/WebSocketServer.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/AbstractAppStorage.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/AppStorageArchive.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/events/NodeEventContainer.java, afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageArchiveTest.java, afs-ws/afs-ws-server-utils/src/main/java/com/powsybl/afs/ws/server/utils/AppDataBean.java, afs-ws/afs-ws-server-utils/src/main/java/com/powsybl/afs/ws/server/utils/SimpleKeyGenerator.java, afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/NodeEventServer.java, afs-ws/afs-ws-server/src/test/java/com/powsybl/afs/ws/server/AppDataBeanMock.java, afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/NodeEventClient.java, pom.xml
Update to powsybl-core v5.3.2
Update to groovy v3.0.15
Update to guava v32.0.1-jre
Update to junit v4.13.1
=> Update to powsybl-core v5.3.2

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
=> Bump 5.2.0-SNAPSHOT

afs-spring-server/pom.xml, afs-spring-server/src/main/java/com/powsybl/afs/server/StorageServer.java, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server-utils/src/main/java/com/powsybl/afs/ws/server/utils/SwaggerConfigExtension.java, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageApplication.java, afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageServer.java, afs-ws/afs-ws-server/src/test/java/com/powsybl/afs/ws/server/SwaggerExtensionTest.java, pom.xml
No
Dependency upgrade
swagger v1.5.20
swagger v2.2.7
=> Swagger update to v2.2.7

afs-action-dsl/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-server/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
=> Prepare release 6.0.0-RC1

pom.xml
=> Fix groovydoc generation during release

afs-action-dsl/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
=> Prepare 6.1.0 version

pom.xml
Fix vulnerabilities in dependencies
=> update swagger and springboot to solve vulnerabilities

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
=> Prepare release 6.2.0

afs-core/src/test/java/com/powsybl/afs/AppFileSystemToolTest.java, afs-local/src/test/java/com/powsybl/afs/local/storage/LocalAppStorageTest.java, afs-storage-api/src/main/java/com/powsybl/afs/storage/AppStorageDataSource.java, pom.xml
No
Dependency update
Core 6.4.1
Core 6.5.0
Covers #157 due to breaking changes in core
=> Update powsybl-core dependency to 6.5.0

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
**_DO NOT SQUASH-MERGE THIS PR_**
=> Prepare release v6.3.0

afs-ext-base/src/test/java/com/powsybl/afs/ext/base/ImportedCaseTest.java, afs-ext-base/src/test/java/com/powsybl/afs/ext/base/VirtualCaseTest.java, pom.xml
No
dependency update
powsybl-core 6.5.0
powsybl-parent v18
powsybl-core 6.6.0
powsybl-parent v20
=> Update powsybl-core dependency to v6.6.0 and powsybl-parent to v20

afs-ext-base/src/test/java/com/powsybl/afs/ext/base/ImportedCaseTest.java, afs-ext-base/src/test/java/com/powsybl/afs/ext/base/VirtualCaseTest.java, pom.xml
No
Dependencies update
Spring 3.3.3
Spring 3.4.0 + junit-jupiter 5.11.3
=> Update Spring Boot dependencies

.github/workflows/snapshot-ci.yml
Same as https://github.com/powsybl/powsybl-metrix/pull/197
=> Fix failure detection in snapshot CI

afs-ws/afs-ws-client-utils/src/test/java/com/powsybl/afs/ws/client/utils/ClientUtilsTest.java
No
New test
the method `ClientUtils.authenticate`is not tested
The method is now tested
=> Add test on ClientUtils.authenticate

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
:warning: **DO NOT MERGE ON GITHUB**
No
Release
v6.5.0-SNAPSHOT
v6.5.0
=> Prepare release v6.5.0

afs-ws/afs-ws-storage/src/test/java/com/powsybl/afs/ws/storage/NodeEventClientReconnectionTest.java
No
CI bug fix
A test fails on GitHub CI, probably due to synchronism issues
Simplified reconnection test assertions by replacing custom `assertTimesOut` with `assertThrows`. Adjusted the reconnection interval and clarified comments for better test reliability and readability. Removed redundant imports and updated tests to improve consistency.
**What changes might users need to make in their …
=> Refactor reconnection test logic and improve readability

.github/workflows/fork-sonar.yml
No
Feature
No SonarCloud integration in the PR
The pull_request trigger was added to enable SonarCloud integration on forks. Permissions were updated to include `contents: read` for better alignment with SonarCloud requirements. These changes ensure proper functionality and security of the workflow. …
=> Add pull_request trigger and update permissions for SonarCloud

.github/workflows/fork-sonar.yml
No
Bug fix
Not working
Decoration + check in the PR from fork
=> Add new permissions and parameters needed for better integration with SonarCloud

.github/workflows/fork-sonar.yml
No
bug fix
No quality gate
Quality gate is added (see https://community.sonarsource.com/t/get-quality-gate-result-from-sonarcloud-analysis-with-github-actions/129850)
=> Enable SonarCloud quality gate wait in workflow.

.github/workflows/fork-build-tests.yml, .github/workflows/fork-sonar.yml
No
bug fix
no check
a sonar check hopefully
Source: https://community.sonarsource.com/t/sonarcloud-github-no-pr-check/68193/22
=> Add HEAD_SHA to workflows for PR checks and Sonar analysis

.github/workflows/fork-sonar.yml
Same as https://github.com/powsybl/powsybl-core/pull/3541
=> Set job-specific permissions for fork-sonar workflow

afs-action-dsl/pom.xml, afs-cassandra/pom.xml, afs-contingency/pom.xml, afs-core/pom.xml, afs-distribution/pom.xml, afs-ext-base/pom.xml, afs-local/pom.xml, afs-mapdb-storage/pom.xml, afs-mapdb/pom.xml, afs-network/afs-network-client/pom.xml, afs-network/afs-network-server/pom.xml, afs-network/pom.xml, afs-scripting/pom.xml, afs-security-analysis-local/pom.xml, afs-security-analysis/pom.xml, afs-spring-server/pom.xml, afs-storage-api/pom.xml, afs-ws/afs-ws-client-utils/pom.xml, afs-ws/afs-ws-client/pom.xml, afs-ws/afs-ws-server-utils/pom.xml, afs-ws/afs-ws-storage/pom.xml, afs-ws/afs-ws-utils/pom.xml, afs-ws/pom.xml, pom.xml
No
Release
v6.6.0-SNAPSHOT
v6.6.0 then v6.7.0-SNAPSHOT
=> Prepare v6.6.0 release
